<html>
<head>
    <title>Динамическое формирование страниц</title>
</head>
<body bgcolor=silver>
<?php
$titles = array("0" => "index", "1" => "First page", "2" => "Second page", "3" => "Third page");
$link = $_GET['link'];
if (!$link) {
    $link = 0;
}
$file = "";
echo("<title>$titles[$link]</title>");
if ($file == "") {
}
if ($link == 1) {
    $file = "script_php3_inc1.html";
}
if ($link == 2) {
    $file = "script_php3_inc2.html";
}
if ($link == 3) {
    $file = "script_php3_inc3.html";
}

if ($file == "") { ?>
    <h3>Пожалуйста, выберите текст:</h3>
    <a href="script_php3.phtml?link=1">текст N1</a><br>
    <a href="script_php3.phtml?link=2">текст N2</a><br>
    <a href="script_php3.phtml?link=3">текст N3</a>
<?php } else {
    include($file);
    if ($link == 1) { ?>
        <br>
        <a href="script_php3.phtml">к оглавлению</a><br>
        <a href="script_php3.phtml?link=2">следующее</a><br>
        <?php
    } elseif ($link == 2) {
        ?>
        <a href="script_php3.phtml">к оглавлению</a><br>
        <a href="script_php3.phtml?link=1">предыдущее</a><br>
        <a href="script_php3.phtml?link=3">следующее</a><br>
        <?php
    } elseif ($link == 3) {
        ?>
        <a href="script_php3.phtml">к оглавлению</a><br>
        <a href="script_php3.phtml?link=2">предыдущее</a><br>
        <?php
    }
}
?>
</body>
</html>